stages:
  - test

.init:
  stage: test
  image: iloveflamingo/buildenv:1.11
  cache:
    paths:
      - __gopath/pkg/mod
  before_script:
    - mkdir ~/.ssh && echo -e "Host gitlab.aoe.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config && echo "${GITLAB_SSH_KEY}" > ~/.ssh/id_rsa && chmod 400 ~/.ssh/id_rsa
    - export GOPATH="$(pwd -P)/__gopath"

cover:
  extends: .init
  script:
    - /pact/pact-go_linux_amd64 daemon &
    - go test -coverprofile cover.out ./...
    - go tool cover -func cover.out

test:
  extends: .init
  script:
    - /pact/pact-go_linux_amd64 daemon &
    - go test -race -vet 'all' ./...

static-check:
  extends: .init
  script:
    - golint -set_exit_status ./...
    - go vet ./...
    #  - gocritic check-project .
